version: '3.4'

services:
    catalog_db:
        container_name: catalog.db
        restart: always
        volumes:
          - ${WEBAPP_STORAGE_HOME}/site:/data/db
        ports:
          - "27017:27017"
    catalog.api:
        environment:
          - ASPNETCORE_ENVIRONMENT=Development
          - "CatalogDatabaseSettings:ConnectionString=mongodb://catalog_db:27017"
        depends_on:
          - catalog_db
        volumes:
          - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
        #  - ${HOME}/.aspnet/https:/root/.aspnet/https/
        ports:
          - "8000:80"
