version: '3.4'

services:
    catalog_db:
        image: mongo
    catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: src/Catalog/Catalog.Api/Dockerfile
